name: eeva
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  connectivity_plus: ^2.3.6
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  intl: ^0.17.0
  dio: ^5.0.3
  json_annotation: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  flutter_lints: ^2.0.1
  rxdart: ^0.27.7
  hive_generator: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Inter-Medium
      fonts:
        - asset: assets/fonts/InterMedium.ttf
    - family: Inter-Bold
      fonts:
        - asset: assets/fonts/InterBold.ttf
    - family: Inter-SemiBold
      fonts:
        - asset: assets/fonts/InterSemiBold.ttf
